DatabaseConsistencySettings:
  color: true
  log_level: INFO

DatabaseConsistencyCheckers:
  All:
    enabled: true

DatabaseConsistencyDatabases:
  primary:
    enabled: true

SchemaMigration:
  enabled: false

ActiveRecord::InternalMetadata:
  enabled: false

Article:
  slug:
    MissingUniqueIndexChecker:
      enabled: false  # slug uniqueness enforced in article_translations (locale, slug) index via Mobility
