# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake
  - rubocop-capybara

AllCops:
  NewCops: enable

Minitest/MultipleAssertions:
  Enabled: false

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
